### PR TITLE
chore: add go report card

### PR DESCRIPTION
**Pull request by firfircelik**

### CODE REVIEW

**Comment by ferhatelmas** [comment]
@firfircelik who is your reviewer ?

**Comment by firfircelik** [comment]
@ferhatelmas review option was disabled. that's why I cannot add you as a reviewer.

**Comment by ferhatelmas** [comment]
OK, thanks.

FYI, it's not disabled but you don't have write access to set it.

**Comment by ferhatelmas** [comment]
In this case, bump others on slack.

**Comment by firfircelik** [comment]
got it.

**Pull request merged**
